name: Go

on:
  push:
    branches: 
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Frontend
      uses: actions/setup-node@master

    - name: Install Dependencies
      run: cd frontend && npm install
      
    - name: Build Vue app
      run: cd frontend && npm run build

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16



    - name: Build
      run: cd ..; go build -v .

    # - name: Run vet & lint
    #   run: |
    #     go vet .
    #     golint .

    - name: Test
      run: go test -v .

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
      with:
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_DASHBOARD_APP}}
        useforce: true
